-- MellowBot / MellowTech Phase 4 schema for Supabase
-- Run this once in Supabase SQL Editor before enabling the database env vars.

create extension if not exists pgcrypto;

create table if not exists public.mellowbot_sessions (
  id uuid primary key default gen_random_uuid(),
  session_id text not null unique,
  first_page text,
  last_page text,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mellowbot_messages (
  id bigint generated by default as identity primary key,
  session_id text not null references public.mellowbot_sessions(session_id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  page_path text,
  intent text,
  service text,
  request_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.mellowbot_leads (
  id bigint generated by default as identity primary key,
  session_id text references public.mellowbot_sessions(session_id) on delete set null,
  source text not null default 'mellowbot',
  customer_name text not null,
  email text,
  phone text,
  service text,
  need text not null,
  details text,
  consent_at timestamptz,
  status text not null default 'new' check (status in ('new','contacted','qualified','won','lost','closed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  service text not null,
  message text not null,
  ip_hash text,
  source text not null default 'contact_form',
  status text not null default 'new' check (status in ('new','read','replied','closed')),
  created_at timestamptz not null default now()
);

create index if not exists idx_mellowbot_messages_session_created on public.mellowbot_messages(session_id, created_at);
create index if not exists idx_mellowbot_leads_status_created on public.mellowbot_leads(status, created_at);
create index if not exists idx_contact_submissions_status_created on public.contact_submissions(status, created_at);

alter table public.mellowbot_sessions enable row level security;
alter table public.mellowbot_messages enable row level security;
alter table public.mellowbot_leads enable row level security;
alter table public.contact_submissions enable row level security;

-- Do not grant browser clients direct table access in Phase 4.
-- The Vercel API uses a Supabase secret key server-side (or the legacy service_role JWT).
revoke all on public.mellowbot_sessions from anon, authenticated;
revoke all on public.mellowbot_messages from anon, authenticated;
revoke all on public.mellowbot_leads from anon, authenticated;
revoke all on public.contact_submissions from anon, authenticated;

grant all on public.mellowbot_sessions to service_role;
grant all on public.mellowbot_messages to service_role;
grant all on public.mellowbot_leads to service_role;
grant all on public.contact_submissions to service_role;

grant usage, select on all sequences in schema public to service_role;
